### ISSUE TITLE
certificationy not registering my answers

### ISSUE THREAD

**Issue by jetcoin** [certificationy/certificationy-cli#10]
When I answer a question, the answer is not registered (blank).
Output:
Your answer: (blank)

So when I'm finished, all the answers are wrong (even though I gave a few correct answers).

Anyone know how I can fix this problem ?

**Comment by mickaelandrieu** [comment]
yes, you can ask to Symfony core team to release 2.7.3 as the last "stable" release is embed with an issue on QuestionHelper we use to display questions and store answers.

They already have fixed the issue, we need to wait for the release.

**Comment by jetcoin** [comment]
Thanks for your response. I tried the dev master branch and the answers are registering fine now.
But now at the end of answering the questions I get this error, which I didn't get before:

[InvalidArgumentException]
The helper "table" is not defined.

**Comment by mickaelandrieu** [comment]
hmm, my bad I wasn't clear on my previous answer, you need to rely on "2.7.x-dev".

Does it solve the issue ?

**Comment by jetcoin** [comment]
Yes it did, thanks alot :)

**Comment by mickaelandrieu** [comment]
you're welcome ;) closed.
