### ISSUE TITLE
Incorrect Yaml::parse usage

### ISSUE THREAD

**Issue by ustrugany** [certificationy/certificationy-cli#15]
While running ```php certificationy.php ``` on  ```((v1.2.0))``` branch got errors:
```php
PHP Warning:  Illegal string offset 'manifest_uri' in /home/piotras/www/certificationy-cli/certificationy.php on line 28
PHP Stack trace:
PHP   1. {main}() /home/piotras/www/certificationy-cli/certificationy.php:0
Starting a new set of 20 questions (available questions: 418)
Question #1 [Bundles] Using Config component, which of these configuration node types are available?
This question IS multiple choice.
```

**Comment by mickaelandrieu** [comment]
I'm not sure it's related to Yaml:: parse,  I will take a look asap

**Comment by ustrugany** [comment]
@mickaelandrieu ok, could you then set exact version here:  https://github.com/certificationy/certificationy/blob/master/composer.json#L22 i guess 2.8 vas last Yaml component version that supported this way of providing arguments: https://github.com/symfony/yaml/blob/2.8/Yaml.php#L50

**Comment by mickaelandrieu** [comment]
@ustrugany to be honest, this is the only debt we have to make certificationy "Symfony3 ready".

Thank you for your contribution, and have a nice day :)
