### ISSUE TITLE
PHP Fatal error:  Cannot access self:: when no class scope is active

### ISSUE THREAD

**Issue by ajax13** [certificationy/certificationy-cli#21]
Hi all,

When I tried to run the "certificationy.php"  I have got this error message:

Executed command:
`php certificationy.php`

Error message:
`PHP Fatal error:  Cannot access self:: when no class scope is active in .../certificationy-cli/certificationy.php on line 25
`
Any help will be appreciated?
Thank you,

**Comment by mickaelandrieu** [comment]
Hi @ajax13,

I've just pushed a new release with the fix https://github.com/certificationy/certificationy-cli/releases/tag/v1.5.0

Sorry about that,

Mickaël

**Comment by ajax13** [comment]
Hi @mickaelandrieu,

I'm very thankful for your swift response!
Really great tool :+1:
