### ISSUE TITLE
"None of the above" answer misplaced

### ISSUE THREAD

**Issue by ntoniazzi** [certificationy/certificationy-cli#22]
In many questions, the answers "All of the above" and "None of the above" are misplaces. Sometimes above the other questions, sometimes below. They should always be the last ones.

**Comment by mickaelandrieu** [comment]
yeah, maybe... I can consider a pull request that change all related questions ;)

**Comment by ntoniazzi** [comment]
https://github.com/certificationy/php-pack/pull/12
