### ISSUE TITLE
Is it extendable?

### ISSUE THREAD

**Issue by spolischook** [certificationy/certificationy-cli#24]
I found that two path is hardcoded in config.yml.
Is there any way to add my own categories with own q/a?

**Comment by mickaelandrieu** [comment]
Hi,

of course, you have to edit the ``config.yml`` file to add the path to your own "packs".

Mickaël

PS: the cli app embed a hard coded configuration for consistency with the old versions (was done to train Symfony certification only).

**Comment by spolischook** [comment]
@mickaelandrieu thank you for your response.
I would like to have  certificationy-cli as dependency in my vendor folder.
Maybe, as temporary solution add to StartCommand -c (--config) parameter.

**Comment by mickaelandrieu** [comment]
Yes, I wanted to add this option and I totaly forgot.

But you're right, I will try to work on this feature asap.

Thank you

**Comment by spolischook** [comment]
@mickaelandrieu it's already don by https://github.com/certificationy/certificationy-cli/pull/29

**Comment by mickaelandrieu** [comment]
@spolischook issue closed, thank you for report 👍
