### ISSUE TITLE
Wrong question count

### ISSUE THREAD

**Issue by mazhuravlev** [certificationy/certificationy-cli#25]
Start command gives question count more than actual questions exist.

```
$ php certificationy.php start --number 1000
Starting a new set of 252 questions (available questions: 425)
$ grep "\-$" vendor/certificationy/*/data/* | wc -l
252
```

**Comment by mickaelandrieu** [comment]
This is weird, I'll take a look...  if you can provide a patch with a test, go for it :)

**Comment by mazhuravlev** [comment]
Looks like Travis [wants 425 questions](https://travis-ci.org/certificationy/certificationy-cli/jobs/153025303#L303), but there are only 252 in fact.

**Comment by mickaelandrieu** [comment]
closed, on my last travis checks this is now good.

Thanks for report!
