### ISSUE TITLE
Wrong answer value from choice list

### ISSUE THREAD

**Issue by elghailani** [certificationy/certificationy-cli#30]
When answering a question, some times the app takes the wrong answer value from a given list.

Example:
When answer N° 2 is submitted, the app takes anwser N° 0 .

![image](https://cloud.githubusercontent.com/assets/2895622/17839755/0507fa3c-67ea-11e6-8386-6dc312636716.png)

**Comment by mickaelandrieu** [comment]
Hi @elghailani,

can you provide a way to reproduce this issue ? I don't like "too much" the "sometimes" part :)

Mickaël

**Comment by elghailani** [comment]
Hi, @mickaelandrieu 
Yeah sure, here is an other occurrence of the issue.

![image](https://cloud.githubusercontent.com/assets/2895622/17840237/42342d32-67f8-11e6-8dc8-aa1f0ceb5f3b.png)

**Comment by mickaelandrieu** [comment]
Curious... I cant reproduce

![cantreproduce](https://cloud.githubusercontent.com/assets/1247388/17840263/5b99afaa-6801-11e6-8959-e72228e22bc6.PNG)
![php55](https://cloud.githubusercontent.com/assets/1247388/17840262/5b99a8f2-6801-11e6-8d5a-04934b8a8ca4.PNG)

Which OS, PHP version and certificationy-cli version do you use ? 

Try to update certificationy-cli (last version v1.5.0), and let me know if you still have the bug.

Mickaël

**Comment by nini** [comment]
Another nice to have would be suppressing auto-complete where answers contain numeric values only. Every time I got a question regarding status codes (301, 302 etc), I selected e.g. option 2) but it actually auto-completed it to 200 and accepted it as an answer. I got it around 5 times, and pressing "Enter" was actually faster than I could correct it. Should I create a new issue for it?

**Comment by mickaelandrieu** [comment]
@nini this isn't so easy to implement, I could consider a unit tested pull request if you can do it :)

**Comment by nini** [comment]
The fix is actually quite simple, here it is https://github.com/certificationy/certificationy-cli/pull/31. I'll try to add a unit test for that, but later (probably next week).

Also I think the original issue caused by a combination of a broken terminal and Symfony autocompletion (which is not visible on the screenshot, but is actually happening).

**Comment by nini** [comment]
Not sure why tests are failing on travis, I didn't change anything there.

**Comment by mickaelandrieu** [comment]
@nini rebase and push force, a YAML error was found in ``php-pack``. This pack is now validated on travis: https://travis-ci.org/certificationy/php-pack/builds/169211551

**Comment by nini** [comment]
Thank you.

**Comment by timonf** [comment]
There is a bug in Symfony's Console component: https://github.com/symfony/symfony/issues/21789

I think, "is_numeric" won't cover answers like "1 and 3" or something else with letters in it.

**Comment by mickaelandrieu** [comment]
@timonf this issue have been already reported to Symfony core team one year ago, I've merged @nini workaround :)
