### ISSUE TITLE
option show-multiple-choice wrong interpreted

### ISSUE THREAD

**Issue by gregoirepaqueron** [certificationy/certificationy-cli#34]
It looks like the option `--show-multiple-choice` is wrongly used.
2 things : 

1. The default value is true, so this option is not useful, maybe it should be replaced by `--hide-multiple-choice` and just detect if the option has been set without looking for its value.
2. No matter the value you set to this option, it will do the opposite of what is intended. Because the value is passed as a string, the test `$showMultipleChoice === true ?` is always wrong cause of the type. So if i try to write `--show-multiple-choice=true` (or any other value btw), i won't have the multiple choice precision.

2 ideas to resolve this : 

1. Set default value at `false`, and just detect if the option is passed, not his value.
2. Correct the test by removing the type test (`== true` instead of `=== true`).
3. Replace this option by `--hide-multiple-choice` and just detect if the option is passed too.

I personnally think the idea n°3 is the best, because this option will be useful only for people who needs to add some difficulty in their practice. Most of the people wants to have this precision, and requiring this option is annoying.

**Comment by mickaelandrieu** [comment]
Hello @gregoirepaqueron,

I'm in favor of 3) too but I don't have to work on it right now: I'm also in favor of a pull request 🍭 

Mickaël

**Comment by gregoirepaqueron** [comment]
@mickaelandrieu sure, i will do a PR soon :smile:
