### ISSUE TITLE
Update to certificationy 2?

### ISSUE THREAD

**Issue by mickaelandrieu** [certificationy/certificationy-cli#37]
It's time to think about certificationy cli v2 :)

I will complete this issue with ideas asap, if you have some don't hesitate to comment :)

Have a nice day

**Comment by BatsaxIV** [comment]
Hi,

A thing that could be nice is a history of tests, with some info like an average score. Maybe a score by type of questions (php, symfony...).
Don't know if that's possible but a histogram with the evolution would be awesome :)

**Comment by mickaelandrieu** [comment]
Everything is possible (I guess :p) ^^

**Comment by mickaelandrieu** [comment]
@BatsaxIV I start to work on represention of a SetScore. Can't tell for now if we can display an histogram in terminal easily in PHP, but this sounds an interesting challenge, right? :)

**Comment by 20uf** [comment]
I think we should have the history of the last tests x, with the duration and an color indicator of the test (in the list), green if > 15 correct answers, orange > 10 and red if it's below (On an average of 20 in this example)

All this is very subjective

It would be nice to have an option "that gives the right answer" **or not**, but it would be especially interesting to have an option that does not display the correct answer but **show an help to find** the right answer. (See PR #33 )

For score charts, it would be necessary to have a number of fixed questions, for example 20, 40 .. on which an average is calculated of the last tests.

I also think that score charts can be calculated on the topics of questions, for php for example: security, oop, functions ... 

These are just ideas.

**Comment by timonf** [comment]
One nice idea: Use the new section-thing from Symfony 4.1, so you can only see one question at once :)

**Comment by mickaelandrieu** [comment]
@timonf Certificationy 2 already exists, you may improve it

**Comment by timonf** [comment]
Yes, of course @mickaelandrieu – Maybe I want to update it aside with my new proposal in certificationy/certificationy :)
