### ISSUE TITLE
Cli tool is now broken

### ISSUE THREAD

**Issue by Antirevel** [certificationy/certificationy-cli#38]
I'm getting an error when running php certificationy.php
"Class 'Certificationy\Certification\Loader' not found"

Reason: class was removed in the following commit
https://github.com/certificationy/certificationy/commit/d6edea30fc369e4e588bdf202843976a75051157

Possible fix: replace "dev-master" by release version number in composer.json
Something like this: "certificationy/certificationy": "~1.4"

**Comment by mickaelandrieu** [comment]
You're right: sounds like I've misunderstood how works composer aliases :/

Should be fixed right now: thanks!

Mickaël
