### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by Guikingone** [certificationy/certificationy-cli#43]
Hi, just starting using this tools for testing my skills and found a bug after the installation (correctly installed, just for precision) : 

```bash
[Symfony\Component\Debug\Exception\FatalThrowableError]  
  Class 'Certificationy\Certification\Loader' not found  
```

The composer install was good, I've PHP on 7.1 version and I'm launching the tools on Mac.

Any idea of the reason why this bug ?

Thanks :)

**Comment by mickaelandrieu** [comment]
Hello @Guikingone,

can you send me the result of `composer info | grep certificationy` please?

Mickaël

**Comment by Guikingone** [comment]
Hello, 

Yes, for sure, here it is : 

```bash
mbpdeguillaume-1:certificationy-cli guillaume$ composer info | grep certificationy
certificationy/certificationy     dev-master 7cb066a A library to create certification system
certificationy/php-pack           dev-master 976dd4e A series of questions to prepare for the Zend PHP5.5 certifica...
certificationy/symfony-pack       dev-master dbcdf44 A series of questions to prepare for the certification Symfony2
```

**Comment by mickaelandrieu** [comment]
Ok, let me publish a new release, I've fixed certificationy version *after* the tag :/

Thanks for report

**Comment by Guikingone** [comment]
Works for me. 

Thanks again :)
