### ISSUE TITLE
ANSI coloring is broken after first answer

### ISSUE THREAD

**Issue by scaytrase** [certificationy/certificationy-cli#49]
I'm using windows, powershell, php 7.2, latest master of this repo

First question is displayed with proper colored text, but after first letter shell codes are shown instead of coloring

![image](https://user-images.githubusercontent.com/6578413/37359640-356d8536-26ff-11e8-959e-c83bf00b72dd.png)

**Comment by mickaelandrieu** [comment]
IMHO, this can be fixed if we upgrade the Symfony version of the Console Component.

I'll try to find time to do it 👍

**Comment by mickaelandrieu** [comment]
Probably fixed in v2 => closed !
