### ISSUE TITLE
Package hirak/prestissimo at version ^0.3 has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version  

### ISSUE THREAD

**Issue by corretge** [certificationy/certificationy-cli#54]
After clone the repo and execute 

```bash
docker compose up
```

I get the error:

Package hirak/prestissimo at version ^0.3 has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version  

Spliting the composer instructions and comment prestissimo, It works well

```bash
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
### RUN composer global require "hirak/prestissimo:0.3" --prefer-dist --no-progress --optimize-autoloader --classmap-authoritative
RUN composer clear-cache
```

**Comment by roukmoute** [comment]
It's been a long time that this repository has not been updated.  
Feel free to do a pull request :)

**Comment by corretge** [comment]
Done!  

https://github.com/certificationy/certificationy-cli/pull/55

many thanks!

**Comment by mickaelandrieu** [comment]
I'm not sure we need this package, so let's consider this "bug" is fixed 👍 

Thanks for the issue 

Regards

**Comment by corretge** [comment]
Thank you for the effort dedicated to the community 👏🏻

the package that doesn't run enables multi-thread download for composer. It's desirable but not necessary.
