### ISSUE TITLE
Start fail

### ISSUE THREAD

**Issue by benjy8001** [certificationy/certificationy-cli#60]
Hi,

I just try you'r awesome tool with simple `make start`. Unfortunately, run the certification tool fail :

```
bash-5.1# php certificationy.php

In Parser.php line 358:

  Duplicate key "question" detected at line 121 (near "            5 PHP EVOL I").


start [--number [NUMBER]] [-l|--list] [--training] [--hide-multiple-choice] [-c|--config [CONFIG]] [--] [<categories>...]
```

Due to this file : vendor/certificationy/php-pack/data/strings-patterns.yml

I see this in composer.json : `certificationy/php-pack": "^1.4"`, and it's true, the file is fucked => https://github.com/certificationy/php-pack/blob/v1.4/data/strings-patterns.yml#L117

So, this need an update (new php-pack release), and a composer update.

I can help if needed :)

**Comment by mickaelandrieu** [comment]
Yes, OMW for a new release.

**Comment by mickaelandrieu** [comment]
Release done, please upgrade and enjoy !
